### ISSUE TITLE
Docker swarm mode

### ISSUE THREAD

**Issue by galindro** [monitoringartist/zabbix-docker-monitoring#71]
@jangaraj, this container works fine in Docker swarm mode? I was wondering this because Docker swarm mode doesn't have privileged flag anymore. How could I deploy It to access Docker metrics? By mounting /var/run/docker.sock?

**Comment by jangaraj** [comment]
I don't know. The best option is to try. In the theory you don't need a privileged flag. But it depends on the OS. selinux/apparmor can block some particular requests - then maybe some selinux/apparmor policy can solve it.

It's only swarm configuration problem, so check swarm doc/[issues](https://github.com/docker/swarmkit/issues/1030) how to solve it. I'm closing issue, because it's not relevant to this project.
