### ISSUE TITLE
"Zabbix-Template-App-Docker-as-host(3.x-only)" fails to import

### ISSUE THREAD

**Issue by richlv** [monitoringartist/zabbix-docker-monitoring#81]
template "Zabbix-Template-App-Docker-as-host(3.x-only)" references items from "Template App Docker as host container - www.monitoringartist.com" and fails to import :

    Cannot find item "docker.cstatus[Crashed]" on "Template App Docker as host - www.monitoringartist.com" used in graph "Container Info".

**Comment by jangaraj** [comment]
Thank you Rihards. That is a hidden template and it's not mentioned in the README. You can expect more issues there because it's untested. I don't prefer concepts of containers as hosts in the Zabbix personally, but you may find it useful for your use case. Feel free to create a pull request if you have some improvements.

**Comment by richlv** [comment]
thanks, got it. maybe it's worth prefixing the file with "UNTESTED" or similar and saying in the readme that such templates are very experimental :)

**Comment by jangaraj** [comment]
Done.
